trigger:
- '*'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 8.x'
  inputs:
    packageType: sdk
    version: '8.x'
    performMultiLevelLookup: true

- task: NodeTool@0
  displayName: 'Use Node 16.x'
  inputs:
    versionSpec: '16.x'
    checkLatest: true

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: 'ci'
    workingDirectory: Tailspin.SpaceGame.Web
    verbose: false

- script: |
    npx sass wwwroot:wwwroot
  displayName: 'Compile Sass assets'
  workingDirectory: Tailspin.SpaceGame.Web

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'

- task: UseDotNet@2
  displayName: 'Use .NET SDK 8.x (default)'
  inputs:
    packageType: 'sdk'
    version: '8.x'   # ← 最後に入れて既定にする